name: Deno Checks

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Check formatting
              run: deno fmt --check

            - name: Check linting
              run: deno lint

            - name: Run tests
              run: deno test
